
namespace backendED
{
    public class edActividad
    {
        public int idactividaddetalle { get; set; }
        public int idactividad { get; set; }
        public string v_pregunta { get; set; }
        public string alternativa_A { get; set; }
        public string alternativa_B { get; set; }
        public string alternativa_C { get; set; }
        public string alternativa_D { get; set; }
        public string alternativa_E { get; set; }
        public string alternativa_F { get; set; }
        public string alternativa_G { get; set; }
        public string alternativa_H { get; set; }
        public string alternativa_I { get; set; }
        public int tipo_pregunta { get; set; }
        public int ipregunta { get; set; }
        public int ifase { get; set; }
        public int puntaje_pregunta { get; set; }
        public int idactividadAlumnodetalle { get; set; }
        public int idactividad_alumno { get; set; }
        public int igrado { get; set; }
        public int isexo { get; set; }
        public string snombres { get; set; }
        public string sapellidos { get; set; }
        public string slugarnacimiento { get; set; }
        public int iedad { get; set; }
        public string scelular { get; set; }
        public string scorreo { get; set; }
        public string scolegio { get; set; }
        public string sdistrito { get; set; }
        public string sugel { get; set; }
        public string scarrera1 { get; set; }
        public string scarrera2 { get; set; }
        public string scarrera3 { get; set; }
        public string scarrera4 { get; set; }
        public string scarrera5 { get; set; }
        public string scomentario { get; set; }
        public string dtfecharegistro { get; set; }
        public string dtfechafin { get; set; }
        public string sclave { get; set; }

        public int id_actividad_alumno_detalle { get; set; }
        public int id_actividad_alumno { get; set; }
        public int id_actividad_detalle { get; set; }
        public int i_fase { get; set; }
        public string v_pregunta_1 { get; set; }
        public string v_pregunta_2 { get; set; }
        public string v_pregunta_3 { get; set; }
        public string v_pregunta_4 { get; set; }
        public string v_pregunta_5 { get; set; }
        public string v_pregunta_6 { get; set; }
        public string v_pregunta_7 { get; set; }
        public string v_pregunta_8 { get; set; }
        public string v_pregunta_9 { get; set; }
        public string v_pregunta_10 { get; set; }
        public string v_pregunta_11 { get; set; }
        public string v_pregunta_12 { get; set; }
        public string v_pregunta_13 { get; set; }
        public string v_pregunta_14 { get; set; }
        public string v_pregunta_15 { get; set; }
        public string v_pregunta_16 { get; set; }
        public string v_pregunta_17 { get; set; }
        public string v_pregunta_18 { get; set; }
        public string v_pregunta_19 { get; set; }
        public string v_pregunta_20 { get; set; }
        public string v_pregunta_21 { get; set; }
        public string v_pregunta_22 { get; set; }
        public string v_pregunta_23 { get; set; }
        public string v_pregunta_24 { get; set; }
        public string v_pregunta_25 { get; set; }
        public string v_pregunta_26 { get; set; }
        public string v_pregunta_27 { get; set; }
        public string v_pregunta_28 { get; set; }
        public string v_pregunta_29 { get; set; }
        public string v_pregunta_30 { get; set; }
        public string v_pregunta_31 { get; set; }
        public string v_pregunta_32 { get; set; }
        public string v_pregunta_33 { get; set; }
        public string v_pregunta_34 { get; set; }
        public string v_pregunta_35 { get; set; }
        public string v_pregunta_36 { get; set; }
        public string v_pregunta_37 { get; set; }
        public string v_pregunta_38 { get; set; }
        public string v_pregunta_39 { get; set; }
        public string v_pregunta_40 { get; set; }
        public string v_pregunta_41 { get; set; }
        public string v_pregunta_42 { get; set; }
        public string v_pregunta_43 { get; set; }
        public string v_pregunta_44 { get; set; }
        public string v_pregunta_45 { get; set; }
        public string v_pregunta_46 { get; set; }
        public string v_pregunta_47 { get; set; }
        public string v_pregunta_48 { get; set; }
        public string v_pregunta_49 { get; set; }
        public string v_pregunta_50 { get; set; }
        public string v_pregunta_51 { get; set; }
        public string v_pregunta_52 { get; set; }
        public string v_pregunta_53 { get; set; }
        public string v_pregunta_54 { get; set; }
        public string v_pregunta_55 { get; set; }
        public string v_pregunta_56 { get; set; }
        public string v_pregunta_57 { get; set; }
        public string v_pregunta_58 { get; set; }
        public string v_pregunta_59 { get; set; }
        public string v_pregunta_60 { get; set; }
        public int i_puntaje { get; set; }
        public string v_descripcion { get; set; }
        public int i_tipo_pregunta { get; set; }
        public int b_estado { get; set; }

        
    }
}
